services:
  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:? "DB_NAME must be set"}
      POSTGRES_PASSWORD: ${DB_PASSWORD:? "DB_PASSWORD must be set"}
      POSTGRES_USER: ${DB_USER:? "DB_USER must be set"}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
  adminer:
    image: adminer:latest
    ports:
      - 9090:8080
  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  database_data:
