name: Test and Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.1'

    - name: Install swaggo
      run: |
        go install github.com/swaggo/swag/cmd/swag@latest
        echo "$GOPATH/bin" >> $GITHUB_PATH

    - name: Generate Swagger
      run: swag init

    - name: Install dependencies
      run: go mod download

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...

    - name: Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
    
    # TODO: Add step to deploy to a server or cloud service if needed
